### ISSUE TITLE
no more activator inspect

### ISSUE THREAD

**Issue by eklavya** [typesafehub/activator#1067]
Hi,

I can't seem to find the inspect option in activator anymore. I remember it used to be there in the 1.1/2 era. What happened to it, is it no more available/freely available?

OS: Mac OS X Yosemite
activator versions tried: 1.3.2, 1.3.5
JDK versions tried: 1.7, 1.8
browsers tried: Safari, Firefox

Regards,

Saurabh Rawat

**Comment by corruptmemory** [comment]
@eklavya,

Inspect support has been discontinued in Acntivator because Typesafe is working on a new monitoring infrastructure that will support more use-cases than only being available in Activator.  The "old" Activator inspect support was provided by [echo](https://github.com/typesafehub/echo) which is open-source, but unmaintained.

You may want to look at [Kamon](http://kamon.io/) as it has a path to production monitoring.

**Comment by adrijardi** [comment]
It would be really nice to include that info on the documentation: http://www.typesafe.com/activator/docs states there is a inspector functionality.

So can we get the functionality we had by manually including the echo plugin? Do we have to downgrade to an earlier version of Activator to keep a functionality that was perfectly usable before until that new "monitoring infrastructure" is ready?

I don't get why the functionality is removed if there is no replacement for it. In general, I am under the impresion that Typesafe is doing a poor job regarding this tools, first with Typesafe Console and now with this. It's disappointing me.
