### ISSUE TITLE
Windows activator.bat isn't working

### ISSUE THREAD

**Issue by donpironet** [typesafehub/activator#986]
My project works fine on my mac but the server it must be deployed on is a windows server. So I typed in the same command:

activator start -Dhttp.port=9090  this works fine on my mac but on windows I get that the command isn't correct and the input line is too long.

So I found some topics and they said you could fix it like this:

activator start '-Dhttp.port=9090' but still the input line is too long and the command is incorrect.

Found some other topics that you need to change the sequence on windows like this:

activator '-Dhttp.port=9090' 'start 9090' 

everytime the same problem...

Could someone help me on this because it really needs to be deployed.

**Comment by havocp** [comment]
You may have some luck with stage instead - see https://www.playframework.com/documentation/2.3.x/Production

The issue could be that your app is in a long directory path and that's enough to make the command line too long, so moving to a less-nested directory might help.

otherwise, you might post the exact error message. If you post on stack overflow there are more people who might answer than on this issue tracker.

**Comment by henrikengstrom** [comment]
Any luck with the suggestions above @donpironet?

**Comment by donpironet** [comment]
No but I solved it by installing Ubuntu.

**Comment by henrikengstrom** [comment]
Reverting to Linux is always a good option ;)

I just ran ``activator -Dhttp.port=9090 start`` on my Windows 8 instance successfully so my guess is, also, that it is path related.

Will close this issue. Please open a new one if run into the issue again and it is helpful is you can provide us with the exact error message.

Thanks for using Activator.
