### ISSUE TITLE
invalid source release: 1.7

### ISSUE THREAD

**Issue by rcalandr** [typesafehub/activator#992]
Hi, i'm trying to run the akka-java-spring template but i get this error "invalid source release: 1.7" when compiling the source with activator ui.
I run on linux and I started activator with this option

./activator -java-home /usr/java/jdk1.7.0_55 -v -d ui

I believe that the problem is related to sbt version or sbt options but i don't know how to fix this. Can someone help me please?

Thanks

Regards

**Comment by havocp** [comment]
Does it work if you use 
`JAVA_HOME=/usr/java/jdk1.7.0_55 PATH=/usr/java/jdk1.7.0_55/bin:"$PATH" activator -v -d ui` 
instead?

Your command line works for me with java 8 here. (I don't have 1.7 installed)

**Comment by rcalandr** [comment]
Hi,

thanks for your response. I need my default java_home to point to java 1.6 (this because all my previous projects need to build with java6....with ant!! :) ). This is the reason why i tried to pass it to the activator. 
I modified the build.sbt from the template removing/commenting
//javacOptions ++= Seq("-source", "1.7", "-target", "1.7")

and the build works so it seems the activator (and also the sbt compile with the same option -java-home) doesn't work for me...
Moreover even if i comment javacOptions, the activator ui builds but remains pending and i cannot run tests or run the project..

Thanks in advance

Regards

**Comment by havocp** [comment]
Note that you can set the `JAVA_HOME` env var only on a single command line, rather than globally.

However, I see now that your issue isn't `-java-home` at all - that controls the Java used to run activator itself, and java 6 would be fine for that.

The issue (assuming this is activator 1.3.x) is that activator is launching a daemon (sbt server) to load the actual build, and your project's build sets `-source 1.7` (presumably because it requires 1.7). The daemon remains running for a couple minutes once launched, so if you run activator again you may get the already-running one which may not match the java used to launch activator. Once the sbt server exits, I _think_ setting the JAVA_HOME env var when you launch activator should change which Java sbt server gets.

**Comment by rcalandr** [comment]
Ok, I tried to change java_home and path only for the current shell. Then i started the activator ui and build the project (with the fully original build.sbt). The build seems to be successfully completed but the activator still remains on "Building Project" so i cannot run/test the project itself.

How can i stop the build from ui? Is there still a problem with the build (there are no error visible and no log file with exception).

P.S.: So is not possible to force the activator to start the sbt server with a specific java compiler?

Thanks a lot for your support

Regards

**Comment by havocp** [comment]
the sbt server is a shared resource, that could be started (in theory) by activator, an IDE, the sbt command line client, or other tools in the future. So it doesn't make sense to force it from a specific client because no client is guaranteed to get a fresh instance. There would need to be a centralized place to configure the JAVA_HOME. I don't think we have implemented such a place (unless @jsuereth remembers differently).

What is the status of the build when it is locked up (see top-right corner, what text is up there)?

Maybe you could minimize a test case project that shows the problem?

**Comment by rcalandr** [comment]
The status is still "Building Project" with a blue circle (top-right corner) and the Full output shows only Completed tasks, no test is still running (i alsa disable the "test on build" flag).

Thanks a lot

**Comment by havocp** [comment]
can you screenshot any logs ?

if you type an sbt command in the search box at the top, does it work?

it's hard for me to debug without access to the project...

**Comment by rcalandr** [comment]
I found the point. the line
fork in run := true
was duplicated so the project remains "building" even if all tasks were completed.

Thanks a lot!

**Comment by rcalandr** [comment]
Just remains the point that you explained below: is there a centralized place to configure the JAVA_HOME?

Thank you for your help.
